#!/usr/bin/env node
// Copies web fonts + JS libraries out of node_modules into ./fonts and ./vendor
// and generates ./fonts/fonts.css (relative URLs, no network needed at render time).
//
//   npm install && python3 scripts/build-cjk-gap-fonts.py && node scripts/setup-assets.mjs
//
// Font sources (all SIL OFL 1.1, from npm):
//   @fontsource-variable/noto-sans-sc   -> "Noto Sans SC"   (variable wght 100-900, Google unicode-range slices)
//   @fontsource-variable/noto-serif-sc  -> "Noto Serif SC"  (variable wght 200-900)
//   @callmebill/lxgw-wenkai-web         -> "LXGW WenKai"    (v1.522: 300 / 400 / 500)
//   + fonts-extra/ gap-filler slices for the Noto fonts (scripts/build-cjk-gap-fonts.py)
//   @fontsource-variable/inter          -> "Inter"          (variable wght 100-900 + opsz, normal/italic)
//   @fontsource-variable/jetbrains-mono -> "JetBrains Mono" (variable wght 100-800, normal/italic)
//   @fontsource/instrument-serif        -> "Instrument Serif" (400 normal/italic)
//   @fontsource-variable/fraunces       -> "Fraunces"       (variable wght/opsz/SOFT/WONK, normal/italic)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const NM = path.join(ROOT, 'node_modules');
const FONTS = path.join(ROOT, 'fonts');
const VENDOR = path.join(ROOT, 'vendor');
const EXTRA_MANIFEST = path.join(ROOT, 'fonts-extra', 'manifest.json');

// css entries: 'file.css' or { file, prefix (for colliding file names), weight (override) }
const FONT_SETS = [
  { family: 'Noto Sans SC', dir: 'noto-sans-sc', pkg: '@fontsource-variable/noto-sans-sc', css: ['wght.css'] },
  { family: 'Noto Serif SC', dir: 'noto-serif-sc', pkg: '@fontsource-variable/noto-serif-sc', css: ['wght.css'] },
  {
    // LXGW WenKai v1.522 sliced by cn-font-split (covers every glyph of the font, unlike Google-style slices).
    family: 'LXGW WenKai', dir: 'lxgw-wenkai', pkg: '@callmebill/lxgw-wenkai-web',
    css: [
      { file: 'lxgwwenkai-light/result.css', prefix: 'light-', weight: '300' },
      { file: 'lxgwwenkai-regular/result.css', prefix: 'regular-', weight: '400' },
      { file: 'lxgwwenkai-medium/result.css', prefix: 'medium-', weight: '500' },
    ],
  },
  { family: 'Inter', dir: 'inter', pkg: '@fontsource-variable/inter', css: ['opsz.css', 'opsz-italic.css'] },
  { family: 'JetBrains Mono', dir: 'jetbrains-mono', pkg: '@fontsource-variable/jetbrains-mono', css: ['wght.css', 'wght-italic.css'] },
  { family: 'Instrument Serif', dir: 'instrument-serif', pkg: '@fontsource/instrument-serif', css: ['400.css', '400-italic.css'] },
  { family: 'Fraunces', dir: 'fraunces', pkg: '@fontsource-variable/fraunces', css: ['full.css', 'full-italic.css'] },
];

function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function mkdirp(p) { fs.mkdirSync(p, { recursive: true }); }
function copy(src, dst) { mkdirp(path.dirname(dst)); fs.copyFileSync(src, dst); }

function buildFonts() {
  rmrf(FONTS);
  mkdirp(path.join(FONTS, 'LICENSES'));
  const out = [];
  const summary = [];
  out.push(`/*
 * fonts.css -- generated by scripts/setup-assets.mjs. Do not edit by hand.
 * All files are local (relative URLs), so pages render without network access.
 *
 * font-family names:
 *   "Noto Sans SC"      CJK sans (hei), variable weight 100-900
 *   "Noto Serif SC"     CJK serif (song), variable weight 200-900
 *   "LXGW WenKai"       CJK kai (handwritten), weights 300 / 400 / 500 (no 700: bold requests get 500 + synthetic bold)
 *   "Inter"             Latin UI sans, variable weight 100-900 (+ opsz axis), normal + italic
 *   "JetBrains Mono"    Latin monospace, variable weight 100-800, normal + italic
 *   "Instrument Serif"  Latin display serif, 400 normal + italic
 *   "Fraunces"          Latin display serif, variable wght 100-900, opsz 9-144, SOFT, WONK, normal + italic
 *
 * CJK faces are split into unicode-range slices (~115-220 woff2 files per weight) covering EVERY code point
 * of the full fonts (Noto: npm slices + gap-filler slices); the browser downloads only the slices it needs.
 * The renderer preloads the slices for all text in the page before frame 0.
 */
`);
  for (const set of FONT_SETS) {
    const pkgDir = path.join(NM, set.pkg);
    const dstDir = path.join(FONTS, set.dir);
    mkdirp(dstDir);
    let faces = 0;
    let bytes = 0;
    out.push(`\n/* ===================== ${set.family}  (${set.pkg}@${JSON.parse(fs.readFileSync(path.join(pkgDir, 'package.json'), 'utf8')).version}) ===================== */\n`);
    const emit = ({ style, weight, file, range }) => {
      out.push(`@font-face {
  font-family: '${set.family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: swap;
  src: url('./${file}') format('woff2');${range ? `\n  unicode-range: ${range.replace(/\s+/g, '')};` : ''}
}
`);
      faces++;
    };
    for (const entry of set.css) {
      const { file: cssFile, prefix = '', weight: weightOverride } = typeof entry === 'string' ? { file: entry } : entry;
      const cssPath = path.join(pkgDir, cssFile);
      const css = fs.readFileSync(cssPath, 'utf8');
      const blocks = css.match(/@font-face\s*{[^}]*}/g) || [];
      for (const block of blocks) {
        // first url(...) only; local() sources are dropped on purpose (never pick up system-installed copies)
        const urlMatch = block.match(/url\(\s*['"]?([^'")]+\.woff2)['"]?\s*\)/);
        if (!urlMatch) throw new Error(`no woff2 url in ${set.pkg}/${cssFile}: ${block}`);
        const srcAbs = path.resolve(path.dirname(cssPath), urlMatch[1]);
        const fileName = prefix + path.basename(srcAbs);
        copy(srcAbs, path.join(dstDir, fileName));
        bytes += fs.statSync(srcAbs).size;
        const get = (prop) => (block.match(new RegExp(`${prop}\\s*:\\s*([^;}]+)`)) || [])[1]?.trim();
        emit({ style: get('font-style') || 'normal', weight: weightOverride || get('font-weight') || '400', file: `${set.dir}/${fileName}`, range: get('unicode-range') });
      }
    }
    // gap-filler slices built by scripts/build-cjk-gap-fonts.py (code points the npm slices leave out)
    const extras = fs.existsSync(EXTRA_MANIFEST) ? JSON.parse(fs.readFileSync(EXTRA_MANIFEST, 'utf8')).filter((e) => e.family === set.family) : [];
    if (extras.length) out.push(`/* ${set.family}: ${extras.length} gap-filler slices (${extras.reduce((s, e) => s + e.chars, 0)} code points missing from the npm slices; source ${extras[0].source}) */\n`);
    for (const e of extras) {
      const srcAbs = path.join(ROOT, 'fonts-extra', e.file);
      copy(srcAbs, path.join(FONTS, e.file));
      bytes += fs.statSync(srcAbs).size;
      emit({ style: e.style, weight: e.weight, file: e.file, range: e.unicodeRange });
    }
    for (const lic of ['LICENSE', 'OFL.txt']) {
      const p = path.join(pkgDir, lic);
      if (fs.existsSync(p)) copy(p, path.join(FONTS, 'LICENSES', `${set.dir}-${lic}`));
    }
    summary.push(`${set.family.padEnd(18)} ${String(faces).padStart(4)} faces  ${(bytes / 1048576).toFixed(1).padStart(5)} MB  -> fonts/${set.dir}/${extras.length ? `  (incl. ${extras.length} gap slices)` : ''}`);
  }
  fs.writeFileSync(path.join(FONTS, 'LICENSES', 'lxgw-wenkai-OFL.txt'),
    'LXGW WenKai v1.522 -- Copyright 2021-2026 LXGW (https://github.com/lxgw/LxgwWenKai), Copyright 2020 The Klee Project Authors.\n' +
    'Licensed under the SIL Open Font License, Version 1.1 (https://openfontlicense.org); full text identical to noto-sans-sc-LICENSE.\n');

  out.push(`
/* ---------- Typographic safety default ----------
 * Chromium's default text-spacing-trim (normal = trim adjacent CJK punctuation) mis-positions adjacent
 * punctuation whose glyphs come from DIFFERENT unicode-range slices: in sliced Noto Serif SC "，。、" collapse
 * on top of each other. Full-width punctuation (space-all) is the GB/T 15834 convention and renders the
 * same for sliced and unsliced fonts. Override per element if you really want trimming.
 */
:root { text-spacing-trim: space-all; }

/* ---------- Recommended stacks (CJK font FIRST for Chinese text so “”‘’…—· use CJK glyphs) ---------- */
:root {
  --font-zh-sans: 'Noto Sans SC', sans-serif;
  --font-zh-serif: 'Noto Serif SC', serif;
  --font-zh-kai: 'LXGW WenKai', 'Noto Serif SC', serif;
  --font-latin-sans: 'Inter', 'Noto Sans SC', sans-serif;      /* Latin-first: for English / numbers */
  --font-mono: 'JetBrains Mono', 'Noto Sans SC', monospace;
  --font-display: 'Instrument Serif', 'Noto Serif SC', serif;
  --font-display-alt: 'Fraunces', 'Noto Serif SC', serif;
}
`);
  fs.writeFileSync(path.join(FONTS, 'fonts.css'), out.join(''));
  console.log(summary.join('\n'));
}

function buildVendor() {
  rmrf(VENDOR);
  // GSAP: core + all (now free) plugins, UMD builds -> window.gsap, window.DrawSVGPlugin, ...
  const gsapDist = path.join(NM, 'gsap', 'dist');
  for (const f of fs.readdirSync(gsapDist)) {
    if (f.endsWith('.min.js')) copy(path.join(gsapDist, f), path.join(VENDOR, 'gsap', f));
  }
  // three.js: ES modules (three.module.js imports ./three.core.js) + addons (examples/jsm)
  for (const f of ['three.module.js', 'three.core.js']) {
    copy(path.join(NM, 'three', 'build', f), path.join(VENDOR, 'three', f));
  }
  fs.cpSync(path.join(NM, 'three', 'examples', 'jsm'), path.join(VENDOR, 'three', 'addons'), { recursive: true });
  // rough.js: IIFE (window.rough) + ESM
  copy(path.join(NM, 'roughjs', 'bundled', 'rough.js'), path.join(VENDOR, 'rough', 'rough.js'));
  copy(path.join(NM, 'roughjs', 'bundled', 'rough.esm.js'), path.join(VENDOR, 'rough', 'rough.esm.js'));
  // d3: UMD (window.d3)
  copy(path.join(NM, 'd3', 'dist', 'd3.min.js'), path.join(VENDOR, 'd3', 'd3.min.js'));
  const versions = {};
  for (const p of ['gsap', 'three', 'roughjs', 'd3']) {
    versions[p] = JSON.parse(fs.readFileSync(path.join(NM, p, 'package.json'), 'utf8')).version;
    for (const lic of ['LICENSE', 'LICENSE.md', 'LICENSE.txt']) {
      const lp = path.join(NM, p, lic);
      if (fs.existsSync(lp)) copy(lp, path.join(VENDOR, 'LICENSES', `${p}-${lic}`));
    }
  }
  fs.writeFileSync(path.join(VENDOR, 'VERSIONS.json'), JSON.stringify(versions, null, 2) + '\n');
  console.log('vendor:', JSON.stringify(versions));
}

buildFonts();
buildVendor();
